### ISSUE TITLE
Issue with Webpack

### ISSUE THREAD

**Issue by Anahkiasen** [Legitcode/tests#13]
As my components require some assets like Sass files, JSON etc, they are compiled by Webpack through karma-webpack. When I try to import `legit-tests` I get a ton of errors which I think are related to JSDom saying I'm missing various modules (fs, child_process, etc). Any idea how to solve that?

**Comment by zackify** [comment]
Yes. I'll work on this tonight. I'll have legit tests grab your webpack
config from your project root and then compile your component.

**Comment by zackify** [comment]
@Anahkiasen what do you think is it he best approach? I was thinking possibly requiring a different module that will run it through webpack first, possibly `import Test from 'legit-tests/compile'`. I know how to fix this issue, just not sure of the best way to do it.

**Comment by Anahkiasen** [comment]
Hm not sure either, how would `compile` work? Can you compile at runtime like that?

**Comment by zackify** [comment]
@Anahkiasen yes, it's really easy with the webpack cli, I'm just asking for input on how it should work. I could make it a configuration option, ex `Test(<Component/>, {compile: true}) and that would look for your webpack config in the root, or optionally you could pass it the location of the config

**Comment by zackify** [comment]
@Anahkiasen do you have a repo up where I can see what the component looks like? I need to see an example, it'll help when I get to this tonight hopefully

**Comment by zackify** [comment]
If I don't get a reply soon, I'll close this

**Comment by bramschulting** [comment]
Hi! I'm running into the same issue, so maybe I can help you out?

**Comment by bramschulting** [comment]
[Here's a gist](https://gist.github.com/bramschulting/eb56f06cf16ff108bd35) of a simple component that uses [style-loader](https://github.com/webpack/style-loader) (and postscss) to load css. If you need more info, let me know!

**Comment by zackify** [comment]
@bramschulting I'm wondering if figuring out a way to ignore imports like that would be the best way. Because you don't really need styling to test a component's functionality. Hmmm

**Comment by bramschulting** [comment]
If you just return and empty object, that would be a great start. Though a key: key object would be even better.

So say you have the following css:
```
.foo {
  /* ... */
}
```

You'd import
```
{
  foo: 'foo'
}
```

That way, you can still `find()` by className and test classes like `.active`.

**Comment by zackify** [comment]
Are you up for working on a pr for this?

**Comment by bramschulting** [comment]
I don't really know how to make some like that, sorry :s

**Comment by zackify** [comment]
Hmm I'll try to think of something. If you use webpack to compile it's as
easy as making a loader. There may be one out there already for converting
CSS to inline styles.

**Comment by bramschulting** [comment]
I am indeed using webpack to compile the .js files.

**Comment by jasonblanchard** [comment]
fwiw, as a temporary solution, we're getting around this by using `proxyquire` (https://github.com/thlorenz/proxyquire) to override non-js imports in our tests.

So for a component in `app/MyComponent.jsx`:
```
import React, { Component } from 'react';
import './MyComponent.scss';

export default MyComponent extends Component {
  render() {
    return <div>Component-ey stuff I want to test.</div>
  }
}
```

The test in `test/MyComponent.test.js` looks like this:
```
const proxyquire = require('proxyquire').noCallThru();
const MyComponent  = proxyquire('../app/MyComponent, { './MyComponent.scss': {}});

// Test code below. Rendering <MyComponent /> will not break the the mocha runner.
....
```

If the component you are testing imports other components that have non-js imports, you need to use the `@global` option when requiring it in your test file:

```
const MyComponent = proxyquire('../app/MyComponent', {
  './NestedComponent.scss: {
    method: {},
    '@global': true
  }
}
```

**Comment by zackify** [comment]
That's awesome, sounds like a good solution too!

**Comment by jasonblanchard** [comment]
Updated my comment above to not use the `@global` option. That was causing some problems in our build complaining about multiple versions of React in some situations.

**Comment by morlay** [comment]
@jasonblanchard 
If not used with css-modules, and just `import` style file,  we could use babel to ignore the imports instead of mock them.

https://github.com/morlay/babel-plugin-transform-require-ignore

```
require('babel-register')({
  'plugins': [
    [
      'babel-plugin-transform-require-ignore',
      {
        extensions: ['.scss']
      }
    ]
  ]
});
```
only for tested in babel@6

For server render we could did the same thing.

**Comment by zackify** [comment]
Closing, I think @morlay's solution is a good enough one!
