### ISSUE TITLE
Usage in browser?

### ISSUE THREAD

**Issue by peteruithoven** [Legitcode/tests#14]
I'm trying to use this project in the browser using JSPM and it looks like it uses `child_process` which isn't supported in the browser. Is there anyway around this?

**Comment by zackify** [comment]
Where is it using child_process?

**Comment by peteruithoven** [comment]
I think it's jsdom actually, which would make sense because it's made to simulate the DOM in Node.js.

**Comment by zackify** [comment]
@peteruithoven ah, so is there anything else I can do? I could make it so you can import it without jsdom

**Comment by peteruithoven** [comment]
That would be awesome. Could usage of jsdom be optional? 
For me the power of this module is readable test code (avoiding `findRenderedDOMComponentWithClass`, `scryRenderedDOMComponentsWithClass` etc). 
I'm writing a project for the browser and not everything will be [universal](https://medium.com/@mjackson/universal-javascript-4761051b7ae9), so being able to run the tests in a browser is necessary.

**Comment by zackify** [comment]
Yes I can make it optional. Since I'm assuming the testutils would work
just fine in a real browser! I should be able to get this done by the
weekend. Geez I need to write some more extensive docs on this thing now 😜

**Comment by peteruithoven** [comment]
With a small test it looked like commenting `import './dom'` makes it work as expected in a browser, with JSPM. I'll try running the tests in the browser.

**Comment by zackify** [comment]
That's what I was assuming.

**Comment by zackify** [comment]
Try this, `npm install legit-tests@beta` (I know I should have tagged that better) and do
`import Test from 'legit-tests/no-dom` let me know how it goes:)

**Comment by peteruithoven** [comment]
Ah I figured out that `beta` (which I can't currently use with JSPM: https://github.com/jspm/npm/issues/61) points to `0.4.3`. I can now easily install it using the following override, making no-dom.js my default entry point. 
``` bash
jspm install npm:legit-tests@0.4.3 -o "{main: 'lib/no-dom.js'}"
```
This works great! 
Thanks to your work on this library I'm much less afraid to explain to team mates how to write unit tests for React code.

**Comment by zackify** [comment]
I'm going to push this to master today!

**Comment by zackify** [comment]
@peteruithoven https://github.com/Legitcode/tests/releases/tag/0.4.4 closing :)

**Comment by peteruithoven** [comment]
For future reference, it can now be installed with jspm with:
```
jspm install npm:legit-tests -o "{main: 'no-dom.js'}"
```
