### ISSUE TITLE
Improve the API

### ISSUE THREAD

**Issue by geowarin** [Legitcode/tests#22]
Hi guys,

I've given it some thoughts and here is what I'd love to see in legit tests:

* Error handling with exceptions
* Be able to differentiate between collections of elements and single elements
* Keep the current result of **find()** in the context so we are able to find elements and execute actions in that context

## Error Handling

It would be easy to throw if somebody tries to call *simulate()*, for instance, without having called *find()* beforehand.
Likewise, we could throw an error if no matching element is found when calling *find()*.

I believe this would make the API easier to apprehend and avoid debugging sessions.

## Multi selection and current context

For the two other proposals, let me give you some examples and you can tell me if you think that's heading in the right direction.

Let's say that we have the following *ButtonComponent*:

    <div>
      <div className="main">
        <button value="ok" onClick={this.props.action1} />
      </div>
      <div className="other">
        <button value="submit" onClick={this.props.action2} />
      </div>
    </div>

If we kept the current element found by the *find()* method as our root, we could do something like this:

    Test(<ButtonComponent/>)
    .find('.main', {root: true}) // this would be implicit because the root will be the component at the beginning
    .find('button', {root: false}) // this would be implicit because the root is now 'main'
    .simulate('click') // click is implicitly done on the root 
    .test(({component}) => {
      expect(component.props.action1).to.have.been.called
    })

For the multi-component selections, maybe we could let the user decide wether he expects a single or an array of elements. The following is inspired by the mongo api, where you can explicitly say you want a single or a "multi" result:

    <div className="component">
      <table className="table1">
        <tr><td>1</td><td>2</td></tr>
        <tr><td>3</td><td>4</td></tr>
     </table>
     <table className="table2">
        <tr><td>5</td><td>6</td></tr>
        <tr><td>7</td><td>8</td></tr>
     </table>
    </div>

We could then either write this:

    Test(<TableComponent/>)
    .find('.table1')
    .find('td', {multi: true})
    .element('td', td => {
      expect(td.length).toEqual(4)
    })

Or:

    Test(<TableComponent/>)
    .find('table', {multi: false}) // this can be the default behavior
    .find('td', {multi: false})
    .element(td => {
      expect(td.getDOMNode().textContent).to.equal('1')
    })

What do you think?

**Comment by zackify** [comment]
Hmm, I don't know. the whole reason for this is that it's supposed to make things simpler, even if we have to do annoying checks to see if something is an array or not. @kenwheeler @dphaener

**Comment by geowarin** [comment]
The reason behind this proposition is to remove some ambiguities in the API.

The middleware idea is awesome. However, legit-test is making a lot of assumptions:

* If the *helpers* object only has the **elements** key, then give the possibility to retrieve the element in the test() method (#9)
* If the object is the only one in the elements then automatically pass it to the element() method (#17)

There are also assumptions about how to order the calls to the API. For instance, calling simulate without calling **find()** beforehand is somewhat moot.
Finally, there is no way to deal with nested elements.

I agree this can always be dealt with on the user side by some refactoring.
My daily job involves is pair programming and TDD.
We have to pair program with people that are new to react or even javascript.
Going nuclear on our components is out of the question so dealing with nested selector has to be possible.

Finally, I don't like not knowing if the API is going to return an array or a single element.

All this makes iteration on components a pain.

I know this is somewhat confusing because I just said in #19 that I would rather always deal with arrays in middlewares.
@kenwheeler pointed out that some middlewares might act on a single element rather than an array.
This is a good point so what I'm thinking is we have to keep the current context (what the user has just *found* inside the DOM) and let the middlewares take some smart decisions about it.
Namely we could always keep the first element is the **multi** flag is set to false and a collection on the other hand.

If you think about it, you are always *finding* some stuff and then have to select the one that you really meant to act on with the **{element: 'this-one'}** option.
I think we can be a little bit more clever and always act on the last element found with the **find()** method.

If you want to have a look at what I'm working on please check https://github.com/geowarin/tests/tree/ahead where I'm trying to implement those ideas.
You'll see that there is a little more complexity in the **find()** middleware but nothing alarming.

I don't think it's the perfect API (and I'd love to have your opinion on the matter) but it does solve some real use cases I'm dealing with at work. That is: not-tested, not-really-well-encapsulated components.

**Comment by zackify** [comment]
Okay, I'm down to try this out and merge it in, will have to be a breaking change obviously. So is your current pull request up to date with the changes your propose?

**Comment by geowarin** [comment]
I will create a new pull request today so we can discuss the code in details. 
I'll close #19 when it's done.

**Comment by zackify** [comment]
Awesome, I really appreciate all of your time and effort put into this!

**Comment by zackify** [comment]
Can I close this?

**Comment by geowarin** [comment]
Since react 0.14 it is no longer possible to find nested DOM elements with the TestUtils so the implementation of this proposition becomes vastly more complex.
Closing.
