### ISSUE TITLE
jsdom and node 12 vs node 4

### ISSUE THREAD

**Issue by NickStefan** [Legitcode/tests#25]
love the library, but doesn't the jsdom dependency make this node 4 only?

Could we possibly make jsDom a peerDependency?

That way one could use a node 12 compatable jsDom such as 3.x.x?

**Comment by zackify** [comment]
I'm not interested in doing this. What reason do you have for being on node
0.12? Peer dependencies are going away in npm 3 too.

**Comment by NickStefan** [comment]
> What reason do you have for being on node
0.12?

I work at a company that uses 12. Convincing everyone to upgrade is kind of political.

I understand that peerDependencies being auto installed is deprecated, but won't the idea of plugin based packages having 'peer dependencies' still be a thing?

**Comment by zackify** [comment]
Shouldn't you be able to install and setup jsdom however you'd like and
just import from legit-tests/no-dom?

**Comment by NickStefan** [comment]
that will work. thanks!

**Comment by zackify** [comment]
Can't believe I didn't think of that :)
