### ISSUE TITLE
README doesn't work as expected with the .test callback

### ISSUE THREAD

**Issue by andrewhathaway** [Legitcode/tests#27]
Hi there.

Your README examples feature you using arrow functions for your callbacks, however when using arrow functions for `.test`, `this.instance` is undefined etc. For example:

Passes:

```javascript
Test(...)
  .test(function() {
    expect(this.instance).toBeDefined();
  });
```

Fails:

```javascript
Test(...)
  .test(() => {
    expect(this.instance).toBeDefined();
  });
```

Just thought I'd let you know. :)

**Comment by dphaener** [comment]
When using an arrow function, you need to grab the instance, so:

```js
Test(...)
.test(({ instance }) => {
  expect(instance).toBeDefined()
})
```

**Comment by zackify** [comment]
This is not a bug. You should read about how arrow functions work.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

**Comment by zackify** [comment]
Thanks for creating an issue though glad there's people out there using this :)

**Comment by andrewhathaway** [comment]
I am aware by how arrow functions work, but your README does not work.
