### ISSUE TITLE
expect JSX?

### ISSUE THREAD

**Issue by vvo** [Legitcode/tests#29]
What do you think of enhancing the API with being able to:

```js
Test(<TestComponent onClick={spy}/>)
.expectJSX(<span onClick={spy}>Hello people!<Label /></span>)
```

?

https://github.com/algolia/react-element-to-jsx-string
https://github.com/algolia/expect-jsx

**Comment by zackify** [comment]
You can include any library you want yourself. In the examples on the
readme, expect is not a part of this, it is included alongside legit tests.
