### ISSUE TITLE
referencing snake-cased class name selectors from .simulate()

### ISSUE THREAD

**Issue by bmakuh** [Legitcode/tests#31]
If I have something like:

```js
Test(<MyComponent />)
  .find('.thumbs-up-button')
  .simulate({ method: 'click', element: '.thumbs-up-button' })
```

It's unclear from the docs how exactly to reference that class name selector from `.simulate` or `.test`, since the only class name examples are one word (e.g. `.box`). Is the above code example supposed to work?

**Comment by zackify** [comment]
You can always console.log this.elements to see what is there. I'm pretty sure the element would just be the name without the dot. Didn't have time to check. @kenwheeler would know.

**Comment by bmakuh** [comment]
Thanks @zackify! I guess mostly I was suggesting that this be clarified in the docs, but you're right—the name without the dot works.

**Comment by bmakuh** [comment]
And thanks for a great lib!

**Comment by zackify** [comment]
Feel free to add to the wiki. I think anyone can? Haha. Thanks for using it
:) expect some updates soon. About to work on a big project soon and will
need to probably add more stuff to this.

**Comment by bmakuh** [comment]
Okay, I went ahead and added an example to the wiki. 

https://github.com/Legitcode/tests/wiki/Bundled-Middleware#simulate

**Comment by zackify** [comment]
Awesome!!
