### ISSUE TITLE
harmony-reflect should be in dependencies

### ISSUE THREAD

**Issue by chadoh** [Legitcode/tests#32]
Hello! This library looks great, but I haven't yet successfully used it. After running `npm i -D legit-tests`, I set up my first test—a test of an `alt` store. And I encountered this:

```
ERROR in ./~/legit-tests/alt/store.js
Module not found: Error: Cannot resolve module 'harmony-reflect' in /.../node_modules/legit-tests/alt
```

I assume I can also add `harmony-reflect` to my package to get around this.

I see that y'all have that library [listed as a devDependency](https://github.com/Legitcode/tests/blob/master/package.json#L41). It should probably be a regular dependency, yeah?

**Comment by zackify** [comment]
Pretty sure you are correct! If @dphaener can't fix this I'll do it tonight. (He did the alt part)

**Comment by dphaener** [comment]
I'm on it @zackify

**Comment by dphaener** [comment]
@chadoh Just submitted a PR to @zackify for this. Also, the 0.5.x branch has been updated for this and published @ 0.5.4

**Comment by chadoh** [comment]
Great, thanks!

**Comment by zackify** [comment]
https://github.com/Legitcode/tests/releases/tag/0.6.3
