### ISSUE TITLE
Release 0.6.3 is broken

### ISSUE THREAD

**Issue by Dignifiedquire** [Legitcode/tests#36]
It seems the [`0.6.3`](https://github.com/Legitcode/tests/releases/tag/0.6.3) release is broken, as it's missing the code from https://github.com/Legitcode/tests/pull/30 in the compiled output

**Comment by zackify** [comment]
Sorry about that. Will push it up tonight.

**Comment by zackify** [comment]
@Dignifiedquire pushed it up, sorry! 0.6.4

**Comment by Dignifiedquire** [comment]
Thanks :)
