### ISSUE TITLE
Support for react 15 in 1.1.x (or when is 2.0 expected?)

### ISSUE THREAD

**Issue by BradHarris** [Legitcode/tests#40]
It looks like this will be happening in v2.0 so I suppose the question is which will happen first?

Could you just bump the dependency in 1.1.x to allow react 15?
or should we wait for 2.0? and what is the release date for that?

Thanks!

**Comment by zackify** [comment]
Sorry, just been really busy, I plan to add simulating events and finding by components and it should be good. But 2.0 will only do shallow rendering. I can add it to 1.1.x really quick for you.

**Comment by zackify** [comment]
Check 1.1.2, should be fixed

**Comment by BradHarris** [comment]
Thank you!

I will attempt updating and close when I've confirmed it works with react 15
