### ISSUE TITLE
React error when testing components that include refs

### ISSUE THREAD

**Issue by aman-dureja** [Legitcode/tests#41]
We have a React class that uses a ref property. It renders perfectly fine in our application and does not have any errors. However, when using Test from legit-tests to run unit tests, they all fail. If the ref property in the original file is commented out or removed, the tests run as expected. With the ref property intact, however, the following error occurs on all the tests:

<img width="743" alt="screen shot 2016-05-05 at 1 42 51 pm" src="https://cloud.githubusercontent.com/assets/13455356/15051568/4c54dd42-12c7-11e6-8ce3-a481a3955761.png">

This issue is reproduced when running unit tests using Test from legit-tests on any React components whose properties include refs. We are running React version 15.0.1.

**Comment by zackify** [comment]
Are you importing react at the top of the file? Legit tests add react as a
global already.

**Comment by aman-dureja** [comment]
We tried both importing React and not importing it. Both ways, the same error still occurs.

**Comment by zackify** [comment]
Are you running your app in development mode so that it shows errors? The only other thing I can think of is if you are rendering the component with refs as a child to the parent that you are testing, maybe. Are you shallow rendering? Really just shooting in the dark here. A code sample would help

**Comment by aman-dureja** [comment]
The issue occurs whenever a ref is present anywhere in the component. Here is a sample of the code for the component that results in the error:

```
import React from 'react';
import ReactDOM from 'react-dom';

const InputField = React.createClass({
    render() {
        return (
            <div className='input' ref='input'/>
        );
    }
});

export default InputField;
```

And here is the code for the unit test:

```
import Test from 'legit-tests';
import InputField from 'forGit';

describe('Testing InputField', () => {

    it('Renders the component', () => {
        Test(<InputField/>);
    });

});
```

With the ref in the component, the error occurs. Without the ref there, the test succeeds.

The React version is 15.0.1, and the legit-tests version is 1.1.1.

Thank you for the help, it is really appreciated!

**Comment by aman-dureja** [comment]
Hi there,

After some more experimenting, I figured out that Test() will render the component with a ref if shallow rendering is used:

```
Test(<InputField/>, {shallow: true});
```

However, while the component does render now, using the .find() function results in the following error:

```
Invariant Violation: findAllInRenderedTree(...): instance must be a composite component
```

Without being able to use .find(), we are unable to simulate events.

On the other hand, using regular rendering with ReactTestUtils works well, and allows for simulating events as expected. We would still like to use legit-tests however, so any more insight into this issue will be greatly appreciated.

Thank you!

**Comment by zackify** [comment]
I will look into it, but if you only need shallow rendering, try out
https://github.com/Legitcode/tests/tree/2.0
